// Code generated by entc, DO NOT EDIT.

package fieldtype

const (
	// Label holds the string label denoting the fieldtype type in the database.
	Label = "field_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"

	// Table holds the table name of the fieldtype in the database.
	Table = "field_types"
	// ArgumentsTable is the table the holds the arguments relation/edge.
	ArgumentsTable = "arguments"
	// ArgumentsInverseTable is the table name for the Argument entity.
	// It exists in this package in order to avoid circular dependency with the "argument" package.
	ArgumentsInverseTable = "arguments"
	// ArgumentsColumn is the table column denoting the arguments relation/edge.
	ArgumentsColumn = "field_type_arguments"
)

// Columns holds all SQL columns for fieldtype fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the FieldType type.
var ForeignKeys = []string{
	"object_type_fields",
}
