// Code generated by entc, DO NOT EDIT.

package argument

const (
	// Label holds the string label denoting the argument type in the database.
	Label = "argument"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description"
	// FieldTypeKind holds the string denoting the type_kind vertex property in the database.
	FieldTypeKind = "type_kind"
	// FieldTypeName holds the string denoting the type_name vertex property in the database.
	FieldTypeName = "type_name"

	// Table holds the table name of the argument in the database.
	Table = "arguments"
)

// Columns holds all SQL columns for argument fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldTypeKind,
	FieldTypeName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Argument type.
var ForeignKeys = []string{
	"field_type_arguments",
}
