// Code generated by entc, DO NOT EDIT.

package argument

const (
	// Label holds the string label denoting the argument type in the database.
	Label = "argument"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind vertex property in the database.
	FieldKind = "kind"

	// Table holds the table name of the argument in the database.
	Table = "arguments"
)

// Columns holds all SQL columns for argument fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldKind,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Argument type.
var ForeignKeys = []string{
	"field_type_arguments",
}
