// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/knabben/ggql/ent/objecttype"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ObjectTypesColumns holds the columns for the "object_types" table.
	ObjectTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: objecttype.DefaultName},
	}
	// ObjectTypesTable holds the schema information for the "object_types" table.
	ObjectTypesTable = &schema.Table{
		Name:        "object_types",
		Columns:     ObjectTypesColumns,
		PrimaryKey:  []*schema.Column{ObjectTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ObjectTypesTable,
	}
)

func init() {
}
