// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/knabben/ggql/ent/argument"
	"github.com/knabben/ggql/ent/predicate"
)

// ArgumentDelete is the builder for deleting a Argument entity.
type ArgumentDelete struct {
	config
	predicates []predicate.Argument
}

// Where adds a new predicate to the delete builder.
func (ad *ArgumentDelete) Where(ps ...predicate.Argument) *ArgumentDelete {
	ad.predicates = append(ad.predicates, ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *ArgumentDelete) Exec(ctx context.Context) (int, error) {
	return ad.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *ArgumentDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *ArgumentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: argument.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: argument.FieldID,
			},
		},
	}
	if ps := ad.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
}

// ArgumentDeleteOne is the builder for deleting a single Argument entity.
type ArgumentDeleteOne struct {
	ad *ArgumentDelete
}

// Exec executes the deletion query.
func (ado *ArgumentDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{argument.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *ArgumentDeleteOne) ExecX(ctx context.Context) {
	ado.ad.ExecX(ctx)
}
