// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/knabben/ggql/ent/argument"
	"github.com/knabben/ggql/ent/fieldtype"
	"github.com/knabben/ggql/ent/predicate"
)

// FieldTypeUpdate is the builder for updating FieldType entities.
type FieldTypeUpdate struct {
	config
	name              *string
	description       *string
	deprecated_reason *string
	type_kind         *string
	type_name         *string
	arguments         map[int]struct{}
	removedArguments  map[int]struct{}
	predicates        []predicate.FieldType
}

// Where adds a new predicate for the builder.
func (ftu *FieldTypeUpdate) Where(ps ...predicate.FieldType) *FieldTypeUpdate {
	ftu.predicates = append(ftu.predicates, ps...)
	return ftu
}

// SetName sets the name field.
func (ftu *FieldTypeUpdate) SetName(s string) *FieldTypeUpdate {
	ftu.name = &s
	return ftu
}

// SetDescription sets the description field.
func (ftu *FieldTypeUpdate) SetDescription(s string) *FieldTypeUpdate {
	ftu.description = &s
	return ftu
}

// SetDeprecatedReason sets the deprecated_reason field.
func (ftu *FieldTypeUpdate) SetDeprecatedReason(s string) *FieldTypeUpdate {
	ftu.deprecated_reason = &s
	return ftu
}

// SetTypeKind sets the type_kind field.
func (ftu *FieldTypeUpdate) SetTypeKind(s string) *FieldTypeUpdate {
	ftu.type_kind = &s
	return ftu
}

// SetTypeName sets the type_name field.
func (ftu *FieldTypeUpdate) SetTypeName(s string) *FieldTypeUpdate {
	ftu.type_name = &s
	return ftu
}

// AddArgumentIDs adds the arguments edge to Argument by ids.
func (ftu *FieldTypeUpdate) AddArgumentIDs(ids ...int) *FieldTypeUpdate {
	if ftu.arguments == nil {
		ftu.arguments = make(map[int]struct{})
	}
	for i := range ids {
		ftu.arguments[ids[i]] = struct{}{}
	}
	return ftu
}

// AddArguments adds the arguments edges to Argument.
func (ftu *FieldTypeUpdate) AddArguments(a ...*Argument) *FieldTypeUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ftu.AddArgumentIDs(ids...)
}

// RemoveArgumentIDs removes the arguments edge to Argument by ids.
func (ftu *FieldTypeUpdate) RemoveArgumentIDs(ids ...int) *FieldTypeUpdate {
	if ftu.removedArguments == nil {
		ftu.removedArguments = make(map[int]struct{})
	}
	for i := range ids {
		ftu.removedArguments[ids[i]] = struct{}{}
	}
	return ftu
}

// RemoveArguments removes arguments edges to Argument.
func (ftu *FieldTypeUpdate) RemoveArguments(a ...*Argument) *FieldTypeUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ftu.RemoveArgumentIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ftu *FieldTypeUpdate) Save(ctx context.Context) (int, error) {
	return ftu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (ftu *FieldTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := ftu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ftu *FieldTypeUpdate) Exec(ctx context.Context) error {
	_, err := ftu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftu *FieldTypeUpdate) ExecX(ctx context.Context) {
	if err := ftu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ftu *FieldTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fieldtype.Table,
			Columns: fieldtype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fieldtype.FieldID,
			},
		},
	}
	if ps := ftu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := ftu.name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldName,
		})
	}
	if value := ftu.description; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldDescription,
		})
	}
	if value := ftu.deprecated_reason; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldDeprecatedReason,
		})
	}
	if value := ftu.type_kind; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldTypeKind,
		})
	}
	if value := ftu.type_name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldTypeName,
		})
	}
	if nodes := ftu.removedArguments; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fieldtype.ArgumentsTable,
			Columns: []string{fieldtype.ArgumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: argument.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftu.arguments; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fieldtype.ArgumentsTable,
			Columns: []string{fieldtype.ArgumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: argument.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ftu.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// FieldTypeUpdateOne is the builder for updating a single FieldType entity.
type FieldTypeUpdateOne struct {
	config
	id                int
	name              *string
	description       *string
	deprecated_reason *string
	type_kind         *string
	type_name         *string
	arguments         map[int]struct{}
	removedArguments  map[int]struct{}
}

// SetName sets the name field.
func (ftuo *FieldTypeUpdateOne) SetName(s string) *FieldTypeUpdateOne {
	ftuo.name = &s
	return ftuo
}

// SetDescription sets the description field.
func (ftuo *FieldTypeUpdateOne) SetDescription(s string) *FieldTypeUpdateOne {
	ftuo.description = &s
	return ftuo
}

// SetDeprecatedReason sets the deprecated_reason field.
func (ftuo *FieldTypeUpdateOne) SetDeprecatedReason(s string) *FieldTypeUpdateOne {
	ftuo.deprecated_reason = &s
	return ftuo
}

// SetTypeKind sets the type_kind field.
func (ftuo *FieldTypeUpdateOne) SetTypeKind(s string) *FieldTypeUpdateOne {
	ftuo.type_kind = &s
	return ftuo
}

// SetTypeName sets the type_name field.
func (ftuo *FieldTypeUpdateOne) SetTypeName(s string) *FieldTypeUpdateOne {
	ftuo.type_name = &s
	return ftuo
}

// AddArgumentIDs adds the arguments edge to Argument by ids.
func (ftuo *FieldTypeUpdateOne) AddArgumentIDs(ids ...int) *FieldTypeUpdateOne {
	if ftuo.arguments == nil {
		ftuo.arguments = make(map[int]struct{})
	}
	for i := range ids {
		ftuo.arguments[ids[i]] = struct{}{}
	}
	return ftuo
}

// AddArguments adds the arguments edges to Argument.
func (ftuo *FieldTypeUpdateOne) AddArguments(a ...*Argument) *FieldTypeUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ftuo.AddArgumentIDs(ids...)
}

// RemoveArgumentIDs removes the arguments edge to Argument by ids.
func (ftuo *FieldTypeUpdateOne) RemoveArgumentIDs(ids ...int) *FieldTypeUpdateOne {
	if ftuo.removedArguments == nil {
		ftuo.removedArguments = make(map[int]struct{})
	}
	for i := range ids {
		ftuo.removedArguments[ids[i]] = struct{}{}
	}
	return ftuo
}

// RemoveArguments removes arguments edges to Argument.
func (ftuo *FieldTypeUpdateOne) RemoveArguments(a ...*Argument) *FieldTypeUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ftuo.RemoveArgumentIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ftuo *FieldTypeUpdateOne) Save(ctx context.Context) (*FieldType, error) {
	return ftuo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (ftuo *FieldTypeUpdateOne) SaveX(ctx context.Context) *FieldType {
	ft, err := ftuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ft
}

// Exec executes the query on the entity.
func (ftuo *FieldTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := ftuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftuo *FieldTypeUpdateOne) ExecX(ctx context.Context) {
	if err := ftuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ftuo *FieldTypeUpdateOne) sqlSave(ctx context.Context) (ft *FieldType, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fieldtype.Table,
			Columns: fieldtype.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  ftuo.id,
				Type:   field.TypeInt,
				Column: fieldtype.FieldID,
			},
		},
	}
	if value := ftuo.name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldName,
		})
	}
	if value := ftuo.description; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldDescription,
		})
	}
	if value := ftuo.deprecated_reason; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldDeprecatedReason,
		})
	}
	if value := ftuo.type_kind; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldTypeKind,
		})
	}
	if value := ftuo.type_name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: fieldtype.FieldTypeName,
		})
	}
	if nodes := ftuo.removedArguments; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fieldtype.ArgumentsTable,
			Columns: []string{fieldtype.ArgumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: argument.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftuo.arguments; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fieldtype.ArgumentsTable,
			Columns: []string{fieldtype.ArgumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: argument.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ft = &FieldType{config: ftuo.config}
	_spec.Assign = ft.assignValues
	_spec.ScanValues = ft.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ftuo.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ft, nil
}
