// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/knabben/ggql/ent/fieldtype"
)

// FieldType is the model entity for the FieldType schema.
type FieldType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// IsDeprecated holds the value of the "is_deprecated" field.
	IsDeprecated bool `json:"is_deprecated,omitempty"`
	// TypeKind holds the value of the "type_kind" field.
	TypeKind bool `json:"type_kind,omitempty"`
	// TypeName holds the value of the "type_name" field.
	TypeName bool `json:"type_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FieldTypeQuery when eager-loading is set.
	Edges              FieldTypeEdges `json:"edges"`
	object_type_fields *int
}

// FieldTypeEdges holds the relations/edges for other nodes in the graph.
type FieldTypeEdges struct {
	// Arguments holds the value of the arguments edge.
	Arguments []*Argument
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ArgumentsOrErr returns the Arguments value or an error if the edge
// was not loaded in eager-loading.
func (e FieldTypeEdges) ArgumentsOrErr() ([]*Argument, error) {
	if e.loadedTypes[0] {
		return e.Arguments, nil
	}
	return nil, &NotLoadedError{edge: "arguments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FieldType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
		&sql.NullString{}, // description
		&sql.NullBool{},   // is_deprecated
		&sql.NullBool{},   // type_kind
		&sql.NullBool{},   // type_name
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*FieldType) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // object_type_fields
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FieldType fields.
func (ft *FieldType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(fieldtype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ft.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		ft.Name = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field description", values[1])
	} else if value.Valid {
		ft.Description = value.String
	}
	if value, ok := values[2].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field is_deprecated", values[2])
	} else if value.Valid {
		ft.IsDeprecated = value.Bool
	}
	if value, ok := values[3].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field type_kind", values[3])
	} else if value.Valid {
		ft.TypeKind = value.Bool
	}
	if value, ok := values[4].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field type_name", values[4])
	} else if value.Valid {
		ft.TypeName = value.Bool
	}
	values = values[5:]
	if len(values) == len(fieldtype.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field object_type_fields", value)
		} else if value.Valid {
			ft.object_type_fields = new(int)
			*ft.object_type_fields = int(value.Int64)
		}
	}
	return nil
}

// QueryArguments queries the arguments edge of the FieldType.
func (ft *FieldType) QueryArguments() *ArgumentQuery {
	return (&FieldTypeClient{ft.config}).QueryArguments(ft)
}

// Update returns a builder for updating this FieldType.
// Note that, you need to call FieldType.Unwrap() before calling this method, if this FieldType
// was returned from a transaction, and the transaction was committed or rolled back.
func (ft *FieldType) Update() *FieldTypeUpdateOne {
	return (&FieldTypeClient{ft.config}).UpdateOne(ft)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ft *FieldType) Unwrap() *FieldType {
	tx, ok := ft.config.driver.(*txDriver)
	if !ok {
		panic("ent: FieldType is not a transactional entity")
	}
	ft.config.driver = tx.drv
	return ft
}

// String implements the fmt.Stringer.
func (ft *FieldType) String() string {
	var builder strings.Builder
	builder.WriteString("FieldType(")
	builder.WriteString(fmt.Sprintf("id=%v", ft.ID))
	builder.WriteString(", name=")
	builder.WriteString(ft.Name)
	builder.WriteString(", description=")
	builder.WriteString(ft.Description)
	builder.WriteString(", is_deprecated=")
	builder.WriteString(fmt.Sprintf("%v", ft.IsDeprecated))
	builder.WriteString(", type_kind=")
	builder.WriteString(fmt.Sprintf("%v", ft.TypeKind))
	builder.WriteString(", type_name=")
	builder.WriteString(fmt.Sprintf("%v", ft.TypeName))
	builder.WriteByte(')')
	return builder.String()
}

// FieldTypes is a parsable slice of FieldType.
type FieldTypes []*FieldType

func (ft FieldTypes) config(cfg config) {
	for _i := range ft {
		ft[_i].config = cfg
	}
}
