// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/knabben/ggql/ent/objecttype"
	"github.com/knabben/ggql/ent/predicate"
)

// ObjectTypeDelete is the builder for deleting a ObjectType entity.
type ObjectTypeDelete struct {
	config
	predicates []predicate.ObjectType
}

// Where adds a new predicate to the delete builder.
func (otd *ObjectTypeDelete) Where(ps ...predicate.ObjectType) *ObjectTypeDelete {
	otd.predicates = append(otd.predicates, ps...)
	return otd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (otd *ObjectTypeDelete) Exec(ctx context.Context) (int, error) {
	return otd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (otd *ObjectTypeDelete) ExecX(ctx context.Context) int {
	n, err := otd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (otd *ObjectTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: objecttype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: objecttype.FieldID,
			},
		},
	}
	if ps := otd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, otd.driver, _spec)
}

// ObjectTypeDeleteOne is the builder for deleting a single ObjectType entity.
type ObjectTypeDeleteOne struct {
	otd *ObjectTypeDelete
}

// Exec executes the deletion query.
func (otdo *ObjectTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := otdo.otd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{objecttype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (otdo *ObjectTypeDeleteOne) ExecX(ctx context.Context) {
	otdo.otd.ExecX(ctx)
}
