// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/knabben/ggql/ent/objecttype"
)

// ObjectType is the model entity for the ObjectType schema.
type ObjectType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ObjectType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ObjectType fields.
func (ot *ObjectType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(objecttype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ot.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		ot.Name = value.String
	}
	return nil
}

// Update returns a builder for updating this ObjectType.
// Note that, you need to call ObjectType.Unwrap() before calling this method, if this ObjectType
// was returned from a transaction, and the transaction was committed or rolled back.
func (ot *ObjectType) Update() *ObjectTypeUpdateOne {
	return (&ObjectTypeClient{ot.config}).UpdateOne(ot)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ot *ObjectType) Unwrap() *ObjectType {
	tx, ok := ot.config.driver.(*txDriver)
	if !ok {
		panic("ent: ObjectType is not a transactional entity")
	}
	ot.config.driver = tx.drv
	return ot
}

// String implements the fmt.Stringer.
func (ot *ObjectType) String() string {
	var builder strings.Builder
	builder.WriteString("ObjectType(")
	builder.WriteString(fmt.Sprintf("id=%v", ot.ID))
	builder.WriteString(", name=")
	builder.WriteString(ot.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ObjectTypes is a parsable slice of ObjectType.
type ObjectTypes []*ObjectType

func (ot ObjectTypes) config(cfg config) {
	for _i := range ot {
		ot[_i].config = cfg
	}
}
