// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/knabben/ggql/ent/objecttype"
)

// ObjectTypeCreate is the builder for creating a ObjectType entity.
type ObjectTypeCreate struct {
	config
	name *string
}

// SetName sets the name field.
func (otc *ObjectTypeCreate) SetName(s string) *ObjectTypeCreate {
	otc.name = &s
	return otc
}

// SetNillableName sets the name field if the given value is not nil.
func (otc *ObjectTypeCreate) SetNillableName(s *string) *ObjectTypeCreate {
	if s != nil {
		otc.SetName(*s)
	}
	return otc
}

// Save creates the ObjectType in the database.
func (otc *ObjectTypeCreate) Save(ctx context.Context) (*ObjectType, error) {
	if otc.name == nil {
		v := objecttype.DefaultName
		otc.name = &v
	}
	return otc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (otc *ObjectTypeCreate) SaveX(ctx context.Context) *ObjectType {
	v, err := otc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (otc *ObjectTypeCreate) sqlSave(ctx context.Context) (*ObjectType, error) {
	var (
		ot    = &ObjectType{config: otc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: objecttype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: objecttype.FieldID,
			},
		}
	)
	if value := otc.name; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: objecttype.FieldName,
		})
		ot.Name = *value
	}
	if err := sqlgraph.CreateNode(ctx, otc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ot.ID = int(id)
	return ot, nil
}
