name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test action
      uses: .
      with:
        URL: "https://api.graph.cool/simple/v1/ciyz901en4j590185wkmexyex"