// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// ObjectType is the predicate function for objecttype builders.
type ObjectType func(*sql.Selector)
