// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Argument is the predicate function for argument builders.
type Argument func(*sql.Selector)

// FieldType is the predicate function for fieldtype builders.
type FieldType func(*sql.Selector)

// ObjectType is the predicate function for objecttype builders.
type ObjectType func(*sql.Selector)
